name: api-with-cloudflare-named-tunnel
on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/api-cloudflare.yml"
      - "app/**"

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 300
    permissions:
      contents: read
    env:
      PORT: 3000
    steps:
      - uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
          sudo dpkg -i cloudflared-linux-amd64.deb || sudo apt-get -f install -y

      - name: Build Docker image
        run: |
          docker build -t my-node-app ./

      - name: Start your app in Docker
        run: |
          docker run -d --name my-node-app -p $PORT:$PORT my-node-app
          sleep 5
          docker ps
          ss -lntp | grep ":$PORT" || (echo "App not listening on $PORT" && exit 1)

      - name: Run Cloudflare Named Tunnel
        env:
          CF_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
        run: |
          nohup cloudflared tunnel --no-autoupdate run --token "$CF_TUNNEL_TOKEN" > cftunnel.log 2>&1 &
          sleep 2
          echo "Tunnel started."

      - name: Keep alive for 5 hours
        run: sleep $((5 * 60 * 60))
